[package]
name = "auction-api"
version = "0.1.0"
authors = ["Hamza Tokuchi <h@mza.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-api = { version = "2.0.0-rc4", default-features = false }
frame-support = { version = "2.0.0-rc4", default-features = false}
auction-traits = { default-features = false, path="../../../../utils/auction/traits" }

[dependencies.parity-scale-codec]
default-features = false
features = ["derive"]
version = "1.3.1"

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
  "frame-support/std",
  "auction-traits/std",
  "parity-scale-codec/std",
]
