[package]
name = "auction-api"
version = "0.1.0"
authors = ["Hamza Tokuchi <h@mza.jp>"]
edition = "2018"

[dependencies.sp-api]
default-features = false
version = "2.0.0-rc5"
path="../../../../../primitives/api" 

[dependencies.frame-support]
default-features = false
version = "2.0.0-rc5"
path = "../../../../../frame/support"

[dependencies.auction-traits]
default-features = false
path="../../../../utils/auction/traits" 

[dependencies.parity-scale-codec]
default-features = false
features = ["derive"]
version = "1.3.1"

[features]
default = ["std"]
std = [
	"sp-api/std",
  "frame-support/std",
  "auction-traits/std",
  "parity-scale-codec/std",
]
