[package]
authors = ['Hamza Tokuchi <h@mza.jp>']
edition = '2018'
name = 'pallet-auction'
version = "2.0.0-rc5"
description = "Pallet for auctions"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies.serde]
version = "1.0.114"
optional = true

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-rc5"
path = "../../../../primitives/runtime"

[dependencies.frame-system]
default-features = false
version = "2.0.0-rc5"
path = "../../../../frame/system"

[dependencies.frame-support]
default-features = false
version = "2.0.0-rc5"
path = "../../../../frame/support"

[dependencies.auction-traits]
default-features = false
path = "../../../utils/auction/traits"

[dependencies.pallet-balances]
default-features = false
version = "2.0.0-rc5"
path = "../../../../frame/balances"

[dependencies.parity-scale-codec]
default-features = false
version = "1.3.4"
features = ["derive"]

[features]
default = ['std']
std = [
  'serde',
  'sp-runtime/std',
	'frame-system/std',
	'frame-support/std',
  'auction-traits/std',
  'pallet-balances/std',
  'parity-scale-codec/std',
]
