[package]
name = "auction-rpc"
version = "2.0.0-rc5"
authors = ["Hamza Tokuchi <h@mza.jp>"]
edition = "2018"

[dependencies.codec]
package = "parity-scale-codec"
version = "1.3.4"

[dependencies.jsonrpc-core]
version = "14.2.0"
[dependencies.jsonrpc-core-client]
version = "14.2.0"
[dependencies.jsonrpc-derive]
version = "14.2.0"

[dependencies.serde]
version = "1.0.114"
features = ["derive"]
optional = true

[dependencies.sp-rpc]
default-features = false
version = '2.0.0-rc5'
path = "../../../../../primitives/rpc"

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-rc5'
path = "../../../../../primitives/runtime"

[dependencies.sp-blockchain]
default-features = false
version = '2.0.0-rc5'
path = "../../../../../primitives/blockchain"

[dependencies.sp-api]
default-features = false 
version = '2.0.0-rc5'
path = "../../../../../primitives/api"

[dependencies.auction-api]
default-features = false 
path = "../auction-api"

[dependencies.node-auction-runtime]
default-features = false 
path = "../../../runtime"


[features]
default = ["std"]
std = [
  "serde",
  "sp-api/std",
  "sp-runtime/std",
  "auction-api/std",
  "node-auction-runtime/std",
]
