[package]
name = "auction-rpc"
version = "0.1.0"
authors = ["Hamza Tokuchi <h@mza.jp>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.0"
serde = { version = "1.0.101", features = ["derive"], optional = true }

sp-rpc = { version = '2.0.0-rc4', default-features = false}
sp-runtime = { version = '2.0.0-rc4', default-features = false}
sp-blockchain = { version = '2.0.0-rc4', default-features = false}
sp-api = { version = '2.0.0-rc4', default-features = false }

auction-api = { path = "../auction-api", default-features = false }
node-auction-runtime = { path = "../../../runtime", default-features = false }

[features]
default = ["std"]
std = [
  "serde",
  "sp-runtime/std",
  "sp-api/std",
  "auction-api/std",
  "node-auction-runtime/std",
]
