[package]
authors = ['Hamza Tokuchi']
edition = '2018'
name = 'pallet-auction'
version = "1.0.0"
license = "Unlicense"
description = "Pallet for auctions"

## Core deps
############################################
[dependencies.frame-support]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../frame/system"

[dependencies.pallet-balances]
default-features = false
version = '2.0.0-alpha.6'
path = '../../../../frame/balances'

[dependencies.orml-traits]
default-features = false
path = "../../../utils/auction/traits"

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.3.0'
#version = '1.0.6'

[dependencies.num-traits]
version = "0.2"
default-features = false

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../primitives/runtime"

############################################
## Dev deps
############################################
[dev-dependencies.sp-core]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../primitives/io"
############################################

[features]
default = ['std']
std = [
	'parity-scale-codec/std',
	'frame-support/std',
	'frame-system/std',
  'pallet-balances/std',
  'sp-runtime/std',
	'orml-traits/std'
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
