[package]
authors = ['Hamza Tokuchi']
edition = '2018'
name = 'pallet-template'
version = "2.0.0-dev"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

## Core deps
############################################
[dependencies.frame-support]
default-features = false
version = "2.0.0-dev"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0-dev"
path = "../../../../frame/system"

[dependencies.pallet-balances]
default-features = false
version = '2.0.0-alpha.5'
path = '../../../../frame/balances'

[dependencies.orml-traits]
default-features = false
path = "../../../utils/auction/traits"

[dependencies.parity-scale-codec]
default-features = false
features = ['derive']
version = '1.3.0'
#version = '1.0.6'

[dependencies.num-traits]
version = "0.2"
default-features = false

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../primitives/runtime"

############################################
## Dev deps
############################################
[dev-dependencies.sp-core]
default-features = false
version = "2.0.0-dev"
path = "../../../../primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-dev"
path = "../../../../primitives/io"

[dev-dependencies.sp-runtime]
default-features = false
version = "2.0.0-dev"
path = "../../../../primitives/runtime"


[features]
default = ['std']
std = [
	'parity-scale-codec/std',
	'frame-support/std',
	'frame-system/std',
  'pallet-balances/std',
  'sp-runtime/std',
	'orml-traits/std'
]
