[package]
name = "auction-traits"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>, Hamza Tokuchi <h@mza.jp>"]
edition = "2018"

[dependencies.serde]
optional = true
version = "1.0.101"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
version = "1.3.0"

[dependencies.sp-std]
default-features = false
version = "2.0.0-alpha.6"

[dependencies.impl-trait-for-tuples]
version = "0.1.3"

[dependencies.sp-io]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../primitives/io"

[dependencies.frame-support]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../frame/support"


[dependencies.num-traits]
version = "0.2"
default-features = false


[dependencies.sp-runtime]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../primitives/runtime"


[dev-dependencies]
clear_on_drop = { version = "0.2.3", features = ["no_cc"] }	# https://github.com/paritytech/substrate/issues/4179

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"num-traits/std",
	"frame-support/std",
]
