[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-auction'
version = "2.0.0-alpha.5"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
sp-std = { version = "2.0.0-alpha.5", default-features = false }
num-traits = { version = "0.2.11", default-features = false }
impl-trait-for-tuples = "0.1.3"

[dependencies.frame-support]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../frame/system"

///////////////////////////////////////////////////////////////
// These were all dev-dependencies, change back TODO(HAMZA)
[dependencies.sp-core]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../primitives/core"

[dependencies.sp-io]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../primitives/io"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-alpha.5"
path = "../../../../primitives/runtime"


[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
  "sp-runtime/std",
  "sp-std/std",
  "num-traits/std",
  "serde",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
