[package]
name = "node-auction-runtime"
version = "2.0.0-rc5"
authors = ["Anonymous"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies.aura]
default-features = false
package = "pallet-aura"
version = "2.0.0-rc5"
path = "../../../frame/aura"

[dependencies.balances]
default-features = false
package = "pallet-balances"
version = "2.0.0-rc5"
path = "../../../frame/balances"

[dependencies.grandpa]
default-features = false
package = "pallet-grandpa"
version = "2.0.0-rc5"
path = "../../../frame/grandpa"

[dependencies.randomness-collective-flip]
default-features = false
package = "pallet-randomness-collective-flip"
version = "2.0.0-rc5"
path = "../../../frame/randomness-collective-flip"

[dependencies.sudo]
default-features = false
package = "pallet-sudo"
version = "2.0.0-rc5"
path = "../../../frame/sudo"

[dependencies.system]
default-features = false
package = "frame-system"
version = "2.0.0-rc5"
path = "../../../frame/system"

[dependencies.timestamp]
default-features = false
package = "pallet-timestamp"
version = "2.0.0-rc5"
path = "../../../frame/timestamp"

[dependencies.transaction-payment]
default-features = false
package = "pallet-transaction-payment"
version = "2.0.0-rc5"
path = "../../../frame/transaction-payment"

[dependencies.sp-block-builder]
path = "../../../primitives/block-builder"
default-features = false
version = "2.0.0-rc5"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
version = "1.3.4"
features = ["derive"]

[dependencies.frame-support]
default-features = false
version = "2.0.0-rc5"
path = "../../../frame/support"

[dependencies.frame-executive]
default-features = false
version = "2.0.0-rc5"
path = "../../../frame/executive"

[dependencies.serde]
version = "1.0.101"
features = ["derive"]
optional=true

[dependencies.sp-api]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/api"

[dependencies.sp-consensus-aura]
default-features = false
version = "0.8.0-rc5"
path = "../../../primitives/consensus/aura"

[dependencies.sp-core]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/core"

[dependencies.sp-inherents]
default-features = false
path = "../../../primitives/inherents"
version = "2.0.0-rc5"

[dependencies.sp-io]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/io"

[dependencies.sp-offchain]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/offchain"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/runtime"

[dependencies.sp-session]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/session"

[dependencies.sp-std]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/std"

[dependencies.sp-transaction-pool]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/transaction-pool"

[dependencies.sp-version]
default-features = false
version = "2.0.0-rc5"
path = "../../../primitives/version"


[dependencies.auction-trait]
default-features = false
path = "../../utils/auction/traits"

[dependencies.auction]
default-features = false
package = "pallet-auction"
version = "2.0.0-rc5"
path = "../pallets/auction"

[dependencies.auction-api]
default-features = false
path = "../pallets/auction/auction-api"

[build-dependencies.wasm-builder-runner]
package = "substrate-wasm-builder-runner"
version = "1.0.5"
path = "../../../utils/wasm-builder-runner"

[features]
default = ["std"]
std = [
	"serde",
	"sudo/std",
	"aura/std",
	"codec/std",
	"sp-io/std",
	"sp-std/std",
	"system/std",
	"sp-api/std",
	"sp-core/std",
	"auction/std",
	"grandpa/std",
	"balances/std",
	"timestamp/std",
	"sp-version/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-offchain/std",
  "auction-api/std",
	"sp-inherents/std",
	"frame-support/std",
  "auction-traits/std",
	"frame-executive/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"transaction-payment/std",
	"sp-transaction-pool/std",
	"randomness-collective-flip/std",
]
