[package]
name = "node-auction"
version = "2.0.0-rc5"
authors = ["Anonymous"]
description = "Substrate Node auction"
edition = "2018"
license = "Unlicense"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-auction"

# Dependencies #
################
[dependencies.structopt]
version = "0.3.8"
[dependencies.jsonrpc-core]
version = "14.0.3"
[dependencies.jsonrpc-core-client]
version = "14.0.3"
[dependencies.jsonrpc-derive]
version = "14.0.3"

[dependencies.sc-cli]
version = "0.8.0-rc5"
path = "../../../client/cli"
features = ["wasmtime"]

[dependencies.sp-core]
version = "2.0.0-rc5"
path = "../../../primitives/core"

[dependencies.sc-executor]
version = "0.8.0-rc5"
path = "../../../client/executor"
features = ["wasmtime"]

[dependencies.sc-service]
version = "0.8.0-rc5"
path = "../../../client/service"
features = ["wasmtime"]

[dependencies.sp-inherents]
version = "2.0.0-rc5"
path = "../../../primitives/inherents"

[dependencies.sc-transaction-pool]
version = "2.0.0-rc5"
path = "../../../client/transaction-pool"

[dependencies.sp-transaction-pool]
version = "2.0.0-rc5"
path = "../../../primitives/transaction-pool"

[dependencies.sc-network]
version = "0.8.0-rc5"
path = "../../../client/network"

[dependencies.sc-consensus-aura]
version = "0.8.0-rc5"
path = "../../../client/consensus/aura"

[dependencies.sp-consensus-aura]
version = "0.8.0-rc5"
path = "../../../primitives/consensus/aura"

[dependencies.sp-consensus]
version = "0.8.0-rc5"
path = "../../../primitives/consensus/common"

[dependencies.sc-consensus]
version = "0.8.0-rc5"
path = "../../../client/consensus/common"

[dependencies.sc-finality-grandpa]
version = "0.8.0-rc5"
path = "../../../client/finality-grandpa"

[dependencies.sp-finality-grandpa]
version = "2.0.0-rc5"
path = "../../../primitives/finality-grandpa"

[dependencies.sc-client-api]
version = "2.0.0-rc5"
path = "../../../client/api"

[dependencies.sp-api]
version = "2.0.0-rc5"
path = "../../../primitives/api"

[dependencies.sc-rpc]
version = "2.0.0-rc5"
path = "../../../client/rpc"

[dependencies.sc-rpc-api]
version = "0.8.0-rc5"
path = "../../../client/rpc-api"

[dependencies.sp-blockchain]
version = "2.0.0-rc5"
path = "../../../primitives/blockchain"

[dependencies.sp-block-builder]
version = "2.0.0-rc5"
path = "../../../primitives/block-builder"

[dependencies.system-rpc]
package = "substrate-frame-rpc-system"
version = "2.0.0-rc5"
path = "../../../utils/frame/rpc/system"

[dependencies.payment-rpc]
package = "pallet-transaction-payment-rpc"
version = "2.0.0-rc5"
path = "../../../frame/transaction-payment/rpc/"

[dependencies.sp-runtime]
version = "2.0.0-rc5"
path = "../../../primitives/runtime"

[dependencies.sc-basic-authorship]
version = "0.8.0-rc5"
path = "../../../client/basic-authorship"

[dependencies.node-auction-runtime]
version = "2.0.0-rc5"
path = "../runtime"

[dependencies.auction-rpc]
version = "2.0.0-rc5"
path = "../pallets/auction/auction-rpc"

#Build Dependencies#
####################
[build-dependencies.substrate-build-script-utils]
version = "2.0.0-rc5"
path = "../../../utils/build-script-utils"

