[package]
name = "auction-traits"
version = "0.0.1"
authors = ["Hamza Tokuchi <h@mza.jp>"]
edition = "2018"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
version = "1.3.0"

[dependencies.serde]
version = "1.0.114"
features = ["derive"]
optional = true

[dependencies.sp-std]
default-features = false
version = "2.0.0-alpha.6"

[dependencies.sp-runtime]
default-features = false
version = "2.0.0-alpha.6"
path = "../../../../primitives/runtime"

[features]
default = ["std"]
std = [
  "serde",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
]
